typography_spectrum: 0.8194513055495918
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.9292620255146176
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.6795018396805972
  brandStrength: 0.8084231619723141
  rhythmicContrast: 0.428290291223675
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  lightness: 0.8693630574271083
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: thoughtsofmine
